#!/usr/bin/python3
import sys


def factoring():
    factor_file = sys.argv[1]
    with open(factor_file) as fd:
        print(" ")
        # for number in fd:
        #     if int(number) % 2 == 0:
        #             print("{}={}*{}".format(number[:-1], int(number) // int(2), 2))
        #             continue
        #     i = 3
        #     while i < int(number) // 2:
        #         if int(number) % i == 0:
        #             break
        #         i = i + 2
        #     print("{}={}*{}".format(number[:-1], int(number) // int(i), i))

factoring()
