#!/usr/bin/python3
import sys
def factoring():
    factor_file = sys.argv[1]
    flag = 0
    with open(factor_file) as fd:
        for number in fd:
            i = 2
            while i < int(number)/2:
                if int(number) % i == 0:
                    break
                if (i > 100):
                    flag = 1
                    break
                i = i + 1
            a = int(number) / int(i)
            print("{}={}*{}".format(number.strip("\n"), int(a), i))

if __name__ == "__main__":
    factoring()
