#!/usr/bin/python3
import sys
def factoring():
    factor_file = sys.argv[1]
    with open(factor_file) as fd:
        for number in fd:
            i = 2
            if int(number) % i == 0:
                    print("{}={}*{}".format(number[:-1], int(number) // int(i), i))
                    continue
            while i < int(number) // 2:
                if int(number) % i == 0:
                    break
                i = i + 1
            print("{}={}*{}".format(number[:-1], int(number) // int(i), i))

factoring()
